using Pkg
Pkg.REPLMode.pkgstr("add HTTP#master")
Pkg.REPLMode.pkgstr("add https://github.com/wookay/Bukdu.jl.git#sevenstars")
Pkg.REPLMode.pkgstr("add https://github.com/wookay/Millboard.jl.git#master")
Pkg.REPLMode.pkgstr("add Documenter#master")
Pkg.REPLMode.pkgstr("add AbstractTrees#master")
Pkg.REPLMode.pkgstr("add https://github.com/wookay/DataLogger.jl#master")
Pkg.REPLMode.pkgstr("add https://github.com/wookay/Poptart.jl#master")
using Bukdu
